[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nx-apphub-cli"
version = "1.0.0"
description = "NX AppHub CLI — Lightweight command-line tool for managing and building applications in Nitrux."
authors = [
    { name = "Uri Herrera", email = "uri_herrera@nxos.org" }
]
license = { text = "BSD-3-Clause" }
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "requests",
    "pyyaml",
    "rich",
    "python-debian",
    "pyelftools"
]

[project.urls]
Homepage = "https://github.com/Nitrux/nx-apphub"

[project.scripts]
nx-apphub-cli = "nx_apphub_cli.cli:main"

[project.optional-dependencies]
dev = ["isort"]

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_first_party = ["nx_apphub_cli"]
skip = [".venv", "build", "dist"]
